package com.newhire.newhire.newhireprocess;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(58eaa83853d4bc295fb5e8b5ced3e5a1)
 */
@org.kie.api.definition.type.Label(value = "MIStoper")
public class MIStoper  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Ready To Stop")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Boolean ready;

    public MIStoper() {
    }

    public MIStoper(java.lang.Boolean ready) {
        this.ready = ready;
    }


    
    public java.lang.Boolean getReady() {
        return this.ready;
    }

    public void setReady(java.lang.Boolean ready) {
        this.ready = ready;
    }
}