package com.newhire.newhire.newhireprocess;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(a0abbdd486abb3bd8a9ef22219001369)
 */
@org.kie.api.definition.type.Label(value = "NewHire")
public class NewHire  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "InterviewerTotal")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer interviewerTotal;
    
    @org.kie.api.definition.type.Label(value = "Candidate Pass Score")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Integer passScore;
    
    @org.kie.api.definition.type.Label(value = "PositionTitle")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String positionTitle;

    public NewHire() {
    }

    public NewHire(java.lang.String positionTitle, java.lang.Integer interviewerTotal, java.lang.Integer passScore) {
        this.positionTitle = positionTitle;
        this.interviewerTotal = interviewerTotal;
        this.passScore = passScore;
    }


    
    public java.lang.Integer getInterviewerTotal() {
        return this.interviewerTotal;
    }

    public void setInterviewerTotal(java.lang.Integer interviewerTotal) {
        this.interviewerTotal = interviewerTotal;
    }
    
    public java.lang.Integer getPassScore() {
        return this.passScore;
    }

    public void setPassScore(java.lang.Integer passScore) {
        this.passScore = passScore;
    }
    
    public java.lang.String getPositionTitle() {
        return this.positionTitle;
    }

    public void setPositionTitle(java.lang.String positionTitle) {
        this.positionTitle = positionTitle;
    }
}